[mgr]
prepend_keymap = [
  { on = "l", run = "plugin smart-enter" },

  { on = "R", run = "shell 'ripdrag $@' --confirm" },

  { on = "<S-w>", run = "shell '~/bin/wallpaper $@' --confirm" },

  { on = "<Backspace>", run = "hidden toggle" }
]
