[config]

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.cava]
input_path = '~/.config/matugen/templates/matugen-cava'
output_path = '~/.config/cava/config'
post_hook = "pkill -USR1 cava"

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/themes/colors.css'

[templates.quick_colors]
input_path = "~/.config/matugen/templates/quick_colors.qml"
output_path = "~/.config/quickshell/widgets/Colors.qml"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.telegram]
input_path = "~/.config/matugen/templates/colors.sh"
output_path = "~/.cache/wal-telegram/colors.sh"
