require("modules.monitors")
require("modules.inputs")
require("modules.gaps_bordder_colors")
require("modules.animation")
require("modules.env_variables")
require("modules.gestures")
require("modules.binds")
