----- НАСТРОЙКА МОНИТОРОВ ------------------------------------------------------
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080@60.00",
	position = "auto",
	scale = "0.7",
})

hl.monitor({
	output = "eDP-1",
	mode = "1920x1200@165",
	position = "0x0",
	scale = "1",
})

----- ПОДКЛЮЧЕНИЕ ДОПОЛНИТЕЛЬНЫХ ФАЙЛОВ С КОНФИГОМ  ----------------------------
local colors = require("colors")

----- АВТОСТАРТ ДЕМОНОВ --------------------------------------------------------
----- АВТОСТАРТ ПРИЛОЖЕНИЙ -----------------------------------------------------

hl.on("hyprland.start", function()
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("quickshell")
	hl.exec_cmd("swaync")
	hl.exec_cmd("waybar -c ~/.config/waybar/config -s ~/.config/waybar/style.css")
	hl.exec_cmd("wl-clip-persist --clipboard regular --display wayland-1")
	hl.exec_cmd("zen-browser", { workspace = "1" })
	hl.exec_cmd("kitty", { workspace = "2" })
	hl.exec_cmd("Telegram", { workspace = "3" })
	hl.exec_cmd("kitty spotify_player", { workspace = "4" })
end)

hl.config({
	misc = {
		vrr = true,
		disable_splash_rendering = true,
	},
})

----- РАЗМЕР КУРСОРА ЧЕРЕЗ ПЕРЕМЕННУЮ ------------------------------------------
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "30")
hl.env("GDK_SCALE", "1.5")

----- РАСКЛАДКА КЛАВИАТУРЫ -----------------------------------------------------
hl.config({
	input = {
		kb_layout = "us,ru",
		kb_options = "grp:win_space_toggle, caps:escape",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = true,
			drag_lock = false,
		},
		sensitivity = 0.7,
	},
})

----- ГАПСЫ, БОРДЕРЫ, ЦВЕТА... -------------------------------------------------
hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 6,
		border_size = 2,
		col = {
			active_border = colors.active_border,
			inactive_border = colors.inactive_border,
		},
		layout = "scrolling",
	},
	decoration = {
		blur = {
			enabled = true,
			size = 5,
			passes = 2,
			vibrancy = 0.4,
			ignore_opacity = true,
		},
		rounding = 20,
		shadow = {
			enabled = true,
			range = 5,
			render_power = 3,
			color = "rgba(0,0,0,0.2)",
		},
		active_opacity = 1.0,
		inactive_opacity = 0.9,
	},
})

----- АНИМАЦИИ -----------------------------------------------------------------
hl.curve("ease", { type = "bezier", points = { { 0.25, 0.1 }, { 0.25, 1.0 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.13, 0.99 }, { 0.29, 1.05 } } })

hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 5,
	bezier = "overshot",
	style = "gnomed",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 5,
	bezier = "ease",
	style = "slide bottom",
})
hl.animation({
	leaf = "windowsMove",
	enabled = true,
	speed = 5,
	bezier = "overshot",
	style = "slide",
})
hl.animation({
	leaf = "layers",
	enabled = true,
	speed = 5,
	bezier = "ease",
	style = "gnomed",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 3,
	bezier = "ease",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 2,
	bezier = "ease",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 5,
	bezier = "overshot",
	style = "slide",
})

hl.config({
	animations = {
		enabled = true,
	},
})

----- НАСТРОЙКА ЛАЙОУТОВ -------------------------------------------------------
hl.config({
	dwindle = {
		preserve_split = true,
	},
})

----- ЖЕСТЫ --------------------------------------------------------------------
hl.config({
	gestures = {
		workspace_swipe_distance = 1000,
		workspace_swipe_forever = true,
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

----- КЛАВИША МОДИФИКАТОР ------------------------------------------------------
local mainMod = "SUPER"

----- ЗАПУСК ПРИЛОЖЕНИЙ --------------------------------------------------------
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("hyprpicker --autocopy"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("swaync-client -t"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("~/bin/wallpaper"))
hl.bind(
	mainMod .. " + R",
	hl.dsp.exec_cmd(
		'~/bin/wallpaper "$(rofi -show files -modes "files:~/bin/not_terminal_utils/rofi_wallpaper" -show-icons -theme .config/rofi/config_wallpaper.rasi 2>&1)"'
	)
)
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("~/bin/wifimenu"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("Telegram"))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("zen-browser"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("steam"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("kitty spotify_player"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("discord"))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("pavucontrol"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("blueman-manager"))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("obsidian"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("sh ~/bin/wifi"))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("catgirldownloader"))

----- ХОТКЕИ -------------------------------------------------------------------
hl.bind("CTRL + SHIFT + Q", hl.dsp.exit())
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind(mainMod .. " + T", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + G", hl.dsp.layout("swapsplit"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd('grim -g "$(slurp)" - | swappy -f -'))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + V", hl.dsp.window.resize({ x = 1100, y = 800 }))
hl.bind(mainMod .. " + P", hl.dsp.window.pin())

hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("hyprctl keyword general:layout dwindle"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("hyprctl keyword general:layout master"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("hyprctl keyword general:layout scrolling"))

hl.bind(mainMod .. " + CTRL + P", hl.dsp.exec_cmd("poweroff"))
hl.bind(mainMod .. " + CTRL + R", hl.dsp.exec_cmd("reboot"))

----- ПЕРЕКЛЮЧЕНИЕ ФОКУСА ------------------------------------------------------
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

----- ПЕРЕКЛЮЧЕНИЕ ВОРКСПЕЙСОВ -------------------------------------------------
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

----- ПЕРЕМЕЩЕНИЕ ОКОН НА ДРУГОЙ ВОРКСПЕЙС -------------------------------------
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

----- ПЕРЕХОД ПО ВОРКСПЕЙСАМ КОЛЕСОМ МЫШИ --------------------------------------
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

----- ПЕРЕМЕЩЕНИЕ И РЕСАЙЗ ОКОН МЫШЬЮ ------------------------------------------
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

----- РЕСАЙЗ -------------------------------------------------------------------
hl.bind(mainMod .. " + CTRL + h", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind(mainMod .. " + CTRL + l", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
hl.bind(mainMod .. " + CTRL + k", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind(mainMod .. " + CTRL + j", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ x = -50, y = 0, relative = true }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ x = 50, y = 0, relative = true }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ x = 0, y = -50, relative = true }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ x = 0, y = 50, relative = true }))

hl.bind("SUPER + SHIFT + H", hl.dsp.window.swap({ direction = "l" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.swap({ direction = "r" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.swap({ direction = "u" }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.swap({ direction = "d" }))
