// Autogenerated by matugen. Do not edit manually.
import QtQuick

QtObject {
    property string primaryColor: "#faba72"
    property string accentColor: "#2b1700"
    property string mutedColor: "#18120c"
}
