// Autogenerated by matugen. Do not edit manually.
import QtQuick

QtObject {
    property string primaryColor: "#81d3e0"
    property string accentColor: "#001f24"
    property string mutedColor: "#0e1415"
}
