// Autogenerated by matugen. Do not edit manually.
import QtQuick

QtObject {
    property string primaryColor: "#dec56d"
    property string accentColor: "#231b00"
    property string mutedColor: "#16130b"
}
