// Autogenerated by matugen. Do not edit manually.
import QtQuick

QtObject {
    property string primaryColor: "{{ colors.primary_fixed_dim.default.hex }}"
    property string accentColor: "{{ colors.on_primary_fixed.default.hex }}"
    property string mutedColor: "{{ colors.surface_dim.default.hex }}"
}
